name: "Login to Harbor and Pull Compiler"
description: "Logs in to the Harbor registry and pulls the FastEdge compiler image."
inputs:
  harbor_login:
    description: "Harbor registry username"
    required: true
  harbor_password:
    description: "Harbor registry password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Harbor
      uses: docker/login-action@v3
      with:
        registry: harbor.p.gc.onl
        username: ${{ inputs.harbor_login }}
        password: ${{ inputs.harbor_password }}

    - name: Pull FastEdge compiler image
      shell: bash
      run: docker pull harbor.p.gc.onl/fastedge/fastedge-apps-compiler:0.0.2
