[package]
name = "sso-guard-gate-only"
version = "0.0.1"
edition = "2021"

[dependencies]
sso-guard = { path = "../../../core/filter", default-features = false, features = ["strip-session-cookie", "alg-hs256"] }
proxy-wasm = { workspace = true }

[lib]
name = "sso_guard_gate_only"
crate-type = ["cdylib"]

