name: Publish sso-gate-only-filter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'edge-sso/core/**'
      - 'edge-sso/templates/gate-only/cdn-filter/**'

jobs:
  publish:
    uses: ./.github/workflows/_publish_rs.yml
    with:
      template: sso-gate-only-filter
      rust_package: sso-guard-gate-only
      working_directory: edge-sso
      output_path: edge-sso/templates/gate-only/cdn-filter/wasm/gate_sso_guard.wasm
      registry_dir: edge-sso/templates/gate-only/cdn-filter
    secrets: inherit
