name: Publish sso-cookie-filter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'edge-sso/core/**'
      - 'edge-sso/templates/cookie/cdn-filter/**'

jobs:
  publish:
    uses: ./.github/workflows/_publish_rs.yml
    with:
      template: sso-cookie-filter
      rust_package: sso-guard-cookie
      working_directory: edge-sso
      output_path: edge-sso/templates/cookie/cdn-filter/wasm/cookie_sso_guard.wasm
      registry_dir: edge-sso/templates/cookie/cdn-filter
    secrets: inherit
