name: Publish totp-filter

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "edge-totp/otp-filter/**"

permissions:
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/_publish_rs.yml
    with:
      template: totp-filter
      rust_package: totp-filter
      working_directory: edge-totp/otp-filter
      output_path: edge-totp/otp-filter/wasm/totp-filter.wasm
      registry_dir: edge-totp/otp-filter
    secrets: inherit
