name: Publish html2md

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'html2md/**'

jobs:
  publish:
    uses: ./.github/workflows/_publish_rs.yml
    with:
      template: html2md
    secrets: inherit
