name: Publish sso-header-auth

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'edge-sso/core/**'
      - 'edge-sso/templates/header/auth-app/**'

jobs:
  publish:
    uses: ./.github/workflows/_publish_js.yml
    with:
      template: sso-header-auth
      working_directory: edge-sso
      build_command: pnpm -C templates/header/auth-app build
      output_path: edge-sso/templates/header/auth-app/wasm/headers-auth-app.wasm
      registry_dir: edge-sso/templates/header/auth-app
    secrets: inherit
